### ISSUE TITLE
Raspberry Pi (RP2040) Debugger Probe Compatibility

### ISSUE THREAD

**Issue by r-colvin** [ghidraninja/game-and-watch-backup#31]
This is an open issue to, if anyone has access, to test the compatibility of the new RP2040 Debug Kit with this project (at this stage I do not have access)

https://www.raspberrypi.com/news/raspberry-pi-debug-probe-a-plug-and-play-debug-kit-for-12/ 

The recommended J-Link Debuggers have some downsides for this project which is undoubtedly popular with many people
1. The J-Link debuggers, esp. the EDU are hard to obtain at this point in time
2. The J-Link debuggers are expensive (even the EDU is substantially more than the $12 Pi Debug Kit)
3. Continue from point 2, the EDU probe is for non-commercial use which may be an issue for some

If the Pi Debug Kit is a viable target, this might open up a lot of access for new users

related to #19 - Cheap debugger

**Comment by ide** [comment]
I put up PR #33 for the Flipper Zero, which uses the same CMSIS-DAP interface as Picoprobe, the firmware the Pico Debug Probe runs. It might work with a $4 Pico and three wires.

Edit: it works with a Picoprobe
