### ISSUE TITLE
Mac os st link issue on step 2

### ISSUE THREAD

**Issue by KsAmJ** [ghidraninja/game-and-watch-backup#7]
I followed the guide and done the exact connections and I am using an st link... ![IMG_20201130_162728.jpg](https://user-images.githubusercontent.com/24935965/100664409-fc77de80-3370-11eb-9824-8d660df7dc2b.jpg)

BUT step 2 always fail... Showing error.. Any ideas or is there some packages or drivers needed for the st link on the mac

BTW I'm on macos big sur and step one run successfully

**Comment by kbeckmann** [comment]
Can you post your logs? They are stored in the `logs` directory.

A common problem is that the openocd version in ubuntu is too old and doesn't have support for this mcu.

**Comment by KsAmJ** [comment]
`Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
openocd/interface_stlink.cfg:1: Error: Can't find interface/stlink.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 60
at file "openocd/flash_stlink.cfg", line 3
at file "openocd/interface_stlink.cfg", line 1
`

**Comment by KsAmJ** [comment]
> Can you post your logs? They are stored in the `logs` directory.
> 
> A common problem is that the openocd version in ubuntu is too old and doesn't have support for this mcu.

`Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
openocd/interface_stlink.cfg:1: Error: Can't find interface/stlink.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 60
at file "openocd/flash_stlink.cfg", line 3
at file "openocd/interface_stlink.cfg", line 1
`

i am on macos bigsur

**Comment by SteveClement** [comment]
@KsAmJ this is probably due to openocd missing the config file for stlink.

I has the same issue on Debian and had to grab the latest package to make it work.

**Comment by KsAmJ** [comment]
How did u manage to do that
Can u walk me through it?

**Comment by kbeckmann** [comment]
> Error: Can't find interface/stlink.cfg in procedure 'script' at file "embedded:startup.tcl"

This indicates that you’re using an “old” version of openocd. You need to build it from git to get the new and good stuff.

**Comment by nezza** [comment]
Yup, looks like OpenOCD is too old. Try `brew install --HEAD openocd` or so
